FROM node:19-alpine as build

WORKDIR /app

# Install and cache app dependencies
COPY package*.json /app
RUN npm install

# Build application
COPY . /app
RUN npm run build


# Production environment
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html

# Copy NGINX config
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Start the server
CMD ["nginx", "-g", "daemon off;"]
