version: '3.7'

services:
  curriculum_vitae_dev:
    container_name: curriculum_vitae_dev
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: tperich/curriculum_vitae:dev
    ports:
      - '5173:5173'
    volumes:
      - './src:/app/src'
    environment:
      - NODE_ENV=development
