FROM node:19-alpine

# Set working directory
WORKDIR /app

# Install app dependencies
COPY package*.json /app
RUN npm install

# Copy the rest of the app files
COPY . /app

# Run dev server
CMD ["npm", "run", "dev", "--", "--host"]
