version: '3.9'

services:
  curriculum_vitae_prod:
    container_name: curriculum_vitae_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: tperich/curriculum_vitae:prod
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=production
