version: '3.7'

services:
  frontend-prod:
    container_name: frontend-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - '.:/app'
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
