version: '3.7'

services:
  frontend-dev:
    container_name: frontend-dev
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=development
