version: '3.7'

services:
  curriculum_vitae_prod:
    container_name: curriculum_vitae_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
