name: Security

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  security-check:
    name: Security check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: false
          file: Dockerfile.prod
          tags: tperich/curriculum_vitae:prod
          outputs: type=docker,dest=/tmp/image.tar

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          input: /tmp/image.tar
          output: trivy-results.sarif
          format: sarif
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Upload Trivy results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif
          wait-for-processing: true
